#!/bin/bash

clean() {
    echo "removing..."
    rm -rf dist/
}

mkdir -p dist

SRC_DIR="src/tools"
DIST_DIR="dist"

declare -A TOOLS
TOOLS=(
  ["network"]="ping.c ip.c route.c lookup.c whois.c subnet.c" "scanner.c"
  ["hash"]="hash.c hashid.c"
)

compile_source() {
    local src_dir="$1"
    local file="$2"
    local output_dir="$3"
    local flags="$4"
    
    gcc "$src_dir/$file" -o "$output_dir/${file%.c}" $flags
}


if [[ "$1" == "clean" ]]; then
    clean
else
    for category in "${!TOOLS[@]}"; do
        tool_list=(${TOOLS[$category]})
        for file in "${tool_list[@]}"; do
            if [ "$category" == "hash" ]; then
                # Add the -lcrypto flag for hash-related tools
                compile_source "$SRC_DIR/$category" "$file" "$DIST_DIR" "-lcrypto"
            else
                compile_source "$SRC_DIR/$category" "$file" "$DIST_DIR" ""
            fi
        done
    done

    compile_source "$SRC_DIR/network" "dns.c" "$DIST_DIR" "-lresolv"
    compile_source "$SRC_DIR/spoofing" "mac.c" "$DIST_DIR"
    compile_source "$SRC_DIR/bruteforce" "dirb.c" "$DIST_DIR"
    compile_source "$SRC_DIR/sniffing" "sniffer.c" "$DIST_DIR" "-lpcap"
    compile_source "$SRC_DIR/editor" "editor.c" "$DIST_DIR"

    echo "Compilation completed. Executables are in the 'dist' directory."
fi