package areacodes

type AreaCode struct {
	State    string
	Country  string
	Timezone int
	Regions  string
}

var AreaCodes = map[int]AreaCode{
	201: {"NJ", "USA", -5, "Hackensack, Jersey City, Union City, Rutherford, Leonia"},
	202: {"DC", "USA", -5, "Washington, District of Columbia"},
	203: {"CT", "USA", -5, "Bridgeport, New Haven, Stamford, Waterbury, Norwalk, Danbury, Greenwich"},
	204: {"MB", "CAN", -6, "Manitoba -- All regions"},
	205: {"AL", "USA", -6, "Birmingham, Huntsville, Tuscaloosa, Anniston"},
	206: {"WA", "USA", -8, "Seattle, Everett"},
	207: {"ME", "USA", -5, "Maine: All regions"},
	208: {"ID", "USA", -7, "Idaho: All regions"},
	209: {"CA", "USA", -8, "Stockton, Modesto, Merced, Oakdale"},
	210: {"TX", "USA", -6, "San Antonio"},
	212: {"NY", "USA", -5, "New York City (Manhattan only)"},
	213: {"CA", "USA", -8, "Los Angeles, Compton"},
	214: {"TX", "USA", -6, "Dallas"},
	215: {"PA", "USA", -5, "Philadelphia, Lansdale, Doylestown, Newtown, Quakertown"},
	216: {"OH", "USA", -5, "Cleveland, Terrace, Independence, Montrose"},
	217: {"IL", "USA", -6, "Springfield, Champaign Urbana, Decatur, Central Illinois"},
	218: {"MN", "USA", -6, "Duluth, Virginia, Moorhead, Brainerd, Wadena"},
	219: {"IN", "USA", -6, "Gary, Hammond, Merrillville, Portage, Michigan City, Valparaiso"},
	224: {"IL", "USA", -6, "Overlay of 847 area code (Chicago)"},
	225: {"LA", "USA", -6, "Baton Rouge and Surrounding Areas"},
	226: {"ON", "CAN", -5, "Overlay of 519 Area Code."},
	228: {"MS", "USA", -6, "Gulfport, Biloxi, Pascagoula, Bay St. Louis"},
	229: {"GA", "USA", -5, "Albany, Valdosta, Thomasville, Bainbridge, Tifton, Americus, Moultrie, Cordele"},
	231: {"MI", "USA", -5, "Muskegon, Traverse City, Big Rapids, Cadillac, Cheboygan"},
	234: {"OH", "USA", -5, "Overlay of 330 area code."},
	239: {"FL", "USA", -5, "Ft. Myers, Naples, Cape Coral, Bonita Springs, Immokalee, Lehigh Acres, Sanibel, Captiva, Pine Island"},
	240: {"MD", "USA", -5, "Overlay of 301 Area Code (Maryland)"},
	242: {"BA", "BHS", -5, "Bahamas"},
	246: {"", "BRB", -4, "Barbados"},
	248: {"MI", "USA", -5, "Troy, Pontiac, Royal Oak, Birmingham, Rochester, Farmington Hills"},
	249: {"ON", "CAN", -5, "Overlay of 705 area code."},
	250: {"BC", "CAN", -8, "British Columbia: Victoria, Kamloops, Kelowna, Prince George, Nanaimo"},
	251: {"AL", "USA", -6, "Mobile, Prichard, Tillmans Corner, Fairhope, Jackson, Gulfshores"},
	252: {"NC", "USA", -5, "Greenville, Rocky Mount, Wilson, New Bern"},
	253: {"WA", "USA", -8, "Tacoma, Kent, Auburn"},
	254: {"TX", "USA", -6, "Waco, Killeen, Temple"},
	256: {"AL", "USA", -6, "Huntsville, Anniston, Decatur, Gadsden, Florence"},
	260: {"IN", "USA", -5, "Fort Wayne, Huntington, Wabash, Lagrange"},
	262: {"WI", "USA", -6, "Green Bay, Appleton, Racine, Kenosha, Oshkosh, Waukesha, Menomonee Falls, West Bend, Sheboygan"},
	264: {"", "AIA", -4, "Anguilla"},
	267: {"PA", "USA", -5, "Overlay of 215 Area Code (Philadelphia Area)"},
	268: {"", "ATG", -4, "Antigua and Barbuda"},
	269: {"MI", "USA", -5, "Kalamazoo, Battle Creek, St. Joseph, Three Rivers, South Haven, Benton Harbor, Sturgis, Hastings"},
	270: {"KY", "USA", -6, "Bowling Green, Paducah, Owensboro, Hopkinsville"},
	276: {"VA", "USA", -5, "Martinsville, Abingdon, Wytheville, Bristol, Marion, Collinsville"},
	281: {"TX", "USA", -6, "Houston, Sugar Land, Buffalo, Airline, Greenspoint, Spring"},
	284: {"BV", "VGB", -4, "British Virgin Islands"},
	289: {"ON", "CAN", -5, "Overlay of 905 area code."},
	301: {"MD", "USA", -5, "Rockville, Silver Spring, Bethesda, Gaithersburg, Frederick, Laurel, Hagerstown"},
	302: {"DE", "USA", -5, "Delaware: All regions"},
	303: {"CO", "USA", -7, "Denver, Littleton, Englewood, Arvada, Boulder, Aurora"},
	304: {"WV", "USA", -5, "West Virginia: All regions"},
	305: {"FL", "USA", -5, "Miami, Perrine, Homestead, Florida Keys"},
	306: {"SK", "CAN", -7, "Saskatchewan: All regions"},
	307: {"WY", "USA", -7, "Wyoming: All regions"},
	308: {"NE", "USA", -6, "Grand Island, Kearney, North Platte, Scottsbluff"},
	309: {"IL", "USA", -6, "Peoria, Bloomington, Rock Island, Galesburg, Macomb"},
	310: {"CA", "USA", -8, "Compton, Santa Monica, Beverly Hills, West LA, Inglewood, Redondo, El Segundo, Culver City, Torrance"},
	312: {"IL", "USA", -6, "Chicago (Downtown area), Wheeling"},
	313: {"MI", "USA", -5, "Detroit, Livonia, Dearborn"},
	314: {"MO", "USA", -6, "Saint Louis, Ladue, Kirkwood, Creve Coeur, Overland, Ferguson"},
	315: {"NY", "USA", -5, "Syracuse, Utica, Watertown, Rome"},
	316: {"KS", "USA", -6, "Wichita, Hutchinson"},
	317: {"IN", "USA", -5, "Indianapolis, Carmel, Fishers, Greenwood"},
	318: {"LA", "USA", -6, "Shreveport, Monroe, Alexandria, Ruston, Natchitoches"},
	319: {"IA", "USA", -6, "Cedar Rapids, Iowa City, Waterloo, Burlington"},
	320: {"MN", "USA", -6, "St. Cloud, Alexandria, Willmar, Little Falls"},
	321: {"FL", "USA", -5, "Brevard County (Cocoa, Melbourne, Eau Gallie, Titusville), Overlay of most of 407 Area Code."},
	323: {"CA", "USA", -8, "Los Angeles, Montebello"},
	325: {"TX", "USA", -6, "Albilene, San Angelo, Brownwood, Synder, Swee"},
	330: {"OH", "USA", -5, "Akron, Youngstown, Canton, Warren, Kent, Alliance, Medina, New Philadelphia"},
	331: {"IL", "USA", -6, "Overlay of the 630 area code."},
	334: {"AL", "USA", -6, "Montgomery, Dothan, Auburn, Selma, Opelika, Phenix City, Tuskegee"},
	336: {"NC", "USA", -5, "Greensboro, Winston Salem, Highpoint, Burlington, Lexington, Asheboro, Reidsville"},
	337: {"LA", "USA", -6, "Lake Charles, Lafayette, New Iberia, Leesville, Opelousas, Crowley"},
	339: {"MA", "USA", -5, "Overlay of 781 area code."},
	340: {"VI", "USA", -4, "U.S. Virgin Islands"},
	343: {"ON", "CAN", -5, "Overlay of 613 area code."},
	345: {"", "CYM", -5, "Cayman Islands"},
	347: {"NY", "USA", -5, "Overlay of 718 Area Code (Bronx, Brooklyn, Queens, Staten Island)."},
	351: {"MA", "USA", -5, "Overlay of 978 area code."},
	352: {"FL", "USA", -5, "Gainesville, Ocala, Leesburg, Brookville"},
	360: {"WA", "USA", -8, "Vancouver, Olympia, Bellingham, Silverdale"},
	361: {"TX", "USA", -6, "Corpus Christi, Victoria"},
	365: {"ON", "CAN", -5, "Overlay of 905 Area Code: Hamilton, Niagara Falls, Markham, Mississauga, Brampton"},
	385: {"UT", "USA", -7, "Overlay of 801 Area Code."},
	386: {"FL", "USA", -5, "Daytona, Deland, Lake City, DeBary, Orange City, New Smyrna Beach, Palatka, Palm Coast"},
	401: {"RI", "USA", -5, "Rhode Island: All regions"},
	402: {"NE", "USA", -6, "Lincoln, Omaha, Norfolk, Columbus"},
	403: {"AB", "CAN", -7, "Alberta: Calgary, Lethbridge, Banff, Medicine Hat, Red Deer"},
	404: {"GA", "USA", -5, "Atlanta"},
	405: {"OK", "USA", -6, "Oklahoma City, Norman, Stillwater, Britton, Bethany, Moore"},
	406: {"MT", "USA", -7, "Montana: All regions"},
	407: {"FL", "USA", -5, "Orlando, Winter Park, Kissimmee, Cocoa, Lake Buena Vista, Melbourne"},
	408: {"CA", "USA", -8, "San Jose, Sunnyvale, Campbell Los Gatos, Salinas, San Martin, Saratoga, Morgan Hill, Gilroy"},
	409: {"TX", "USA", -6, "Galveston, Beaumont, Port Arthur, Texas City, Nederland"},
	410: {"MD", "USA", -5, "Baltimore, Annapolis, Towson, Catonsville, Glen Burnie"},
	412: {"PA", "USA", -5, "Pittsburgh"},
	413: {"MA", "USA", -5, "Springfield, Pittsfield, Holyoke, Amherst"},
	414: {"WI", "USA", -6, "Milwaukee, Greendale, Franklin, Cudahy, St. Francis, Brown Deer, Whitefish Bay"},
	415: {"CA", "USA", -8, "San Francisco"},
	416: {"ON", "CAN", -5, "Toronto"},
	417: {"MO", "USA", -6, "Joplin, Springfield, Branson, Lebanon"},
	418: {"QC", "CAN", -5, "Quebec"},
	419: {"OH", "USA", -5, "Toledo, Lima, Mansfield, Sandusky, Findlay"},
	423: {"TN", "USA", -5, "Chattanooga, Cleveland, Johnson City, Bristol, Kingsport, Athens, Morristown, Greeneville"},
	424: {"CA", "USA", -8, "Overlay of 310 Area Code"},
	425: {"WA", "USA", -8, "Bothell, Everett, Bellevue, Kirkland, Renton"},
	430: {"TX", "USA", -6, "Overlay of 903 Area Code."},
	431: {"MB", "CAN", -6, "Manitoba - Overlay of 204 Area Code"},
	432: {"TX", "USA", -6, "Midland, Terminal, Odessa, Big Spring, Alpine, Pecos, Fort Stockton"},
	434: {"VA", "USA", -5, "Lynchburg, Danville, Charlottesville, Madison Heights, South Boston"},
	435: {"UT", "USA", -7, "Logan, St. George, Park City, Tooele, Brigham City, Richfield, Moab, Blanding"},
	437: {"ON", "CAN", -5, "Overlay of 647 Area Code (Toronto)"},
	438: {"QC", "CAN", -5, "Overlay of 514 Area Code."},
	440: {"OH", "USA", -5, "Willoughby, Hillcrest, Trinity, Lorain, Elyria"},
	441: {"BM", "BMU", -4, "Bermuda"},
	442: {"CA", "USA", -8, "Overlay of 760 area code."},
	443: {"MD", "USA", -5, "Overlay of 410 Area Code"},
	450: {"QC", "CAN", -5, "Quebec: Laval, Saint Lambert, Longueuil, Sainte Therese"},
	456: {"", "USA", 0, "Used for premium-rate calling"},
	458: {"OR", "USA", -8, "Overlay of 541 Area Code."},
	469: {"TX", "USA", -6, "Overlay of 214, 972 Area Codes (Greater Dallas Area)."},
	470: {"GA", "USA", -5, "Overlay of 404, 678, 770."},
	473: {"", "GRD", -4, "Grenada"},
	475: {"CT", "USA", -5, "Overlay of 203 area code."},
	478: {"GA", "USA", -5, "Macon, Warner Robbins, Dublin, Milledgeville, Forsyth"},
	479: {"AR", "USA", -6, "Fort Smith, Fayetteville, Rogers, Bentonville, Russellville"},
	480: {"AZ", "USA", -7, "Mesa, Scottsdale, Tempe, Chandler, Gilbert"},
	484: {"PA", "USA", -5, "Overlay of 610 Area Code (Allentown, Reading, Bethlehem Area)"},
	500: {"", "USA", 0, "Used for Personal Communication Services"},
	501: {"AR", "USA", -6, "Little Rock, Hot Springs"},
	502: {"KY", "USA", -5, "Louisville, Frankfort, Fort Knox, Pleasure Ridge Park"},
	503: {"OR", "USA", -8, "Portland, Salem, Beaverton, Gresham, Hillsboro"},
	504: {"LA", "USA", -6, "New Orleans, Metairie, Kenner, Chalmette"},
	505: {"NM", "USA", -7, "New Mexico: Albuquerque, Bernalillo, Farmington, Gallup, Grants, Las Vegas, Los Alamos, Rio Rancho, Santa Fe"},
	506: {"NB", "CAN", -4, "New Brunswick: All regions"},
	507: {"MN", "USA", -6, "Rochester, Mankato, Winona, Faribault, Luverne"},
	508: {"MA", "USA", -5, "Worcester, Framingham, Brockton, Plymouth, New Bedford, Marlboro, Natick, Taunton, Auburn, Westboro, Easton"},
	509: {"WA", "USA", -8, "Spokane, Yakima, Walla Walla, Pullman, Kenwick"},
	510: {"CA", "USA", -8, "Oakland, Fremont, Newark, Hayward, Richmond"},
	512: {"TX", "USA", -6, "Austin, San Marcos, Round Rock, Dripping Springs"},
	513: {"OH", "USA", -5, "Cincinnati, Hamilton, Clermont, Middleton, Mason"},
	514: {"QC", "CAN", -5, "Province of Quebec: Montreal Area"},
	515: {"IA", "USA", -6, "Des Moines, Ames, Jefferson"},
	516: {"NY", "USA", -5, "Nassau County: Hempstead, Oceanside, Freeport, Long Beach, Garden City, Glen Cove, Mineola"},
	517: {"MI", "USA", -5, "Lansing, Bay City, Jackson, Howell, Adrian"},
	518: {"NY", "USA", -5, "Albany, Schenectady, Troy, Glens Falls, Saratoga Springs, Lake Placid"},
	519: {"ON", "CAN", -5, "Ontario: London Area, Kitchener, Cambridge, Windsor"},
	520: {"AZ", "USA", -7, "Tucson, Sierra Vista, Nogales, Douglass, Bisbee"},
	530: {"CA", "USA", -8, "Chico, Redding, Marysville, Auburn, Davis, Placerville"},
	531: {"NE", "USA", -6, "Overlay of 402 Area Code."},
	533: {"", "USA", 0, "Used for Personal Communication Services"},
	534: {"WI", "USA", -6, "Overlay of 715 area code."},
	539: {"OK", "USA", -6, "Overlay of 918 area code."},
	540: {"VA", "USA", -5, "Roanoke, Harrisonburg, Fredericksburg, Blacksburg, Winchester, Staunton, Culpeper"},
	541: {"OR", "USA", -8, "Eugene, Medford, Corvallis, Bend, Albany, Roseburg, Klamath Falls"},
	544: {"", "USA", 0, "Used for Personal Communication Services"},
	551: {"NJ", "USA", -5, "Overlay of 201 area code."},
	559: {"CA", "USA", -8, "Fresno, Visalia, Madera, San Joaquin, Porterville, Hanford"},
	561: {"FL", "USA", -5, "Palm Beaches, Boca Raton, Boynton Beach"},
	562: {"CA", "USA", -8, "Long Beach, Norwalk, Alamitos, Downey, Whittier, Lakewood, La Habra"},
	563: {"IA", "USA", -6, "Davenport, Dubuque, Clinton, Muscatine, Decorah, Manchester, West Union"},
	567: {"OH", "USA", -5, "Overlay of 419 area code."},
	570: {"PA", "USA", -5, "Wilkes-Barre, Scranton, Stroudsburg, Williamsport, Pittston"},
	571: {"VA", "USA", -5, "Overlay of 703 area code."},
	573: {"MO", "USA", -6, "Columbia, Cape Girardeau, Jefferson City"},
	574: {"IN", "USA", -5, "South Bend, Elkhart, Mishawaka, Granger, La Porte"},
	575: {"NM", "USA", -7, "Split of 505 area code. Alamogordo, Carlsbad, Clovis, Deming, El Rito, Galina, Hatch, Hobbs, Las Cruces, Penasco, Raton, Taos"},
	579: {"QC", "CAN", -5, "Overlay of 450 Area Code."},
	580: {"OK", "USA", -6, "Lawton, Enid, Ponca City, Ardmore, Duncan"},
	581: {"QC", "CAN", -5, "Overlay of 418 Area Code."},
	585: {"NY", "USA", -5, "Rochester, East Rochester, Olean, Batavia, Webster, Fairport, Henrietta"},
	586: {"MI", "USA", -5, "Warren, Mount Clemens, Roseville, Center Line, Utica, Romeo, Richmond, Washington, New Baltimore"},
	587: {"AB", "CAN", -7, "Overlay of 403 and 780 Area Codes."},
	601: {"MS", "USA", -6, "Southern Mississippi: Jackson, Hattiesburg, Vicksburg, Meridian"},
	602: {"AZ", "USA", -7, "Phoenix"},
	603: {"NH", "USA", -5, "New Hampshire: All regions"},
	604: {"BC", "CAN", -8, "British Columbia: Vancouver, Richmond, New Westminster"},
	605: {"SD", "USA", -6, "South Dakota: All regions"},
	606: {"KY", "USA", -5, "Ashland, Winchester, Pikeville, Somerset"},
	607: {"NY", "USA", -5, "Elmira, Ithaca, Stamford, Binghamton, Endicott, Oneonta"},
	608: {"WI", "USA", -6, "Madison, La Crosse, Janesville, Middleton, Monroe, Platteville, Dodgeville"},
	609: {"NJ", "USA", -5, "Atlantic City, Trenton, Princeton, Pleasantville, Fort Dix, Lawrenceville"},
	610: {"PA", "USA", -5, "Allentown, Reading, Bethlehem, West Chester, Pottstown"},
	611: {"", "USA", 0, "Used for telephone repair service in many Areas"},
	612: {"MN", "USA", -6, "Minneapolis, Richfield"},
	613: {"ON", "CAN", -5, "Ontario East: Ottawa, Kingston, Belleville, Cornwall, Kanata"},
	614: {"OH", "USA", -5, "Columbus, Worthington, Dublin, Reynoldsburg, Westerville, Gahanna, Hilliard"},
	615: {"TN", "USA", -6, "Nashville, Mufreesboro, Hendersonville, Frank"},
	616: {"MI", "USA", -5, "Grand Rapids, Holland, Grand Haven, Greenville, Zeeland, Ionia"},
	617: {"MA", "USA", -5, "Boston, Cambridge, Quincy, Newton, Brookline, Brighton, Somerville, Dorchester, Hyde Park, Jamaica Plain"},
	618: {"IL", "USA", -6, "Collinsville, Alton, Carbondale, Belleville, Mount Vernon, Centralia"},
	619: {"CA", "USA", -8, "San Diego, Chula Vista, El Cajon, La Mesa, National City, Coronado"},
	620: {"KS", "USA", -6, "Hutchinson, Emporia, Liberal, Pittsburg, Dodge City, Garden City, Coffeyville"},
	623: {"AZ", "USA", -7, "Glendale, Sun City, Peoria"},
	626: {"CA", "USA", -8, "Pasadena, Alhambra, Covina, El Monte, La Puenta"},
	630: {"IL", "USA", -6, "La Grange, Roselle, Hinsdale, Downers Grove, Naperville, Lombard, Elmhurst, Aurora, Wheaton"},
	631: {"NY", "USA", -5, "Suffolk County: Brentwood, Farmingdale, Central Islip, Riverhead, Huntington, Deer Park, Amityville, Lindenhurst"},
	636: {"MO", "USA", -6, "St. Charles, Fenton, Harvester, Chesterfield, Manchester"},
	639: {"SK", "CAN", -7, "Overlay of 306 area code"},
	641: {"IA", "USA", -6, "Fairfield, Mason City, Grinnell, Newton, Knoxville"},
	646: {"NY", "USA", -5, "Overlay of 212 Area Code (New York City)."},
	647: {"ON", "CAN", -5, "Overlay of 416 (Toronto)."},
	649: {"", "TCA", -5, "Turks & Caicos Islands"},
	650: {"CA", "USA", -8, "South San Francisco, Palo Alto, San Mateo, Mountain View, Redwood City"},
	651: {"MN", "USA", -6, "St. Paul, Redwing, Farmington, Eagan, Lino Lakes, North Branch, Roseville Valley"},
	657: {"CA", "USA", -8, "Overlay of 714 area code."},
	660: {"MO", "USA", -6, "Warrensburg, Kirksville, Sedalia, Chillicothe, Moberly, Marshall"},
	661: {"CA", "USA", -8, "Bakersfield, Santa Clarita, Palmdale, Simi Valley"},
	662: {"MS", "USA", -6, "Northern Mississippi: Tupelo, Columbus, Greenwood, Greenville, Oxford"},
	664: {"", "MSR", -4, "Montserrat"},
	667: {"MD", "USA", -5, "Overlay of 410, 443 area codes"},
	669: {"CA", "USA", -8, "Overlay of 408 area code (San Jose, San Jose, Sunnyvale, etc.)"},
	670: {"MP", "MNP", 10, "Commonwealth of Northern Mariana Islands (Saipan)"},
	671: {"GU", "GUM", 10, "Guam"},
	678: {"GA", "USA", -5, "Overlay of 404 & 770 area codes."},
	680: {"PW", "PLW", 9, "Palau"},
	681: {"WV", "USA", -5, "Overlay of 304 Area Code."},
	682: {"TX", "USA", -6, "Overlay of 817 area code."},
	684: {"AS", "ASM", -11, "American Samoa"},
	691: {"FM", "FSM", 11, "Federated States of Micronesia"},
	692: {"MH", "MHL", 12, "Marshall Islands"},
	700: {"", "USA", 0, "Used for Value Added Special Services"},
	701: {"ND", "USA", -6, "North Dakota: All regions"},
	702: {"NV", "USA", -8, "Las Vegas & Surrounding Areas."},
	703: {"VA", "USA", -5, "Arlington, Alexandria, Fairfax, Falls Church, Quantico, Herndon, Vienna"},
	704: {"NC", "USA", -5, "Charlotte, Asheville, Gastonia, Concord, Statesville, Salisbury, Shelby, Monroe"},
	705: {"ON", "CAN", -5, "Eastern Ontario: North Bay, Sault Sainte Marie, Barrie, Sudbury, Peterborough, Lindsay, Huntsville"},
	706: {"GA", "USA", -5, "Augusta, Columbus, Athens, Rome, Dalton"},
	707: {"CA", "USA", -8, "Eureka, Napa, Santa Rosa, Petaluma, Vallejo"},
	708: {"IL", "USA", -6, "Oak Brook, Calumet City, Harvey (South suburbs of Chicago)"},
	709: {"NL", "CAN", -4, "Newfoundland and Labrador: All regions. Note: Newfoundland ISLAND's time zone is - 3 hours & 30 minutes."},
	710: {"", "USA", 0, "Federal Government Special Services"},
	712: {"IA", "USA", -6, "Sioux City, Council Bluffs, Spencer, Cherokee, Denison"},
	713: {"TX", "USA", -6, "Houston"},
	714: {"CA", "USA", -8, "Anaheim, Santa Anna"},
	715: {"WI", "USA", -6, "Eau Claire, Wausau, Stevens Point, Superior"},
	716: {"NY", "USA", -5, "Buffalo, Niagara Falls, Tonawanda, Williamsville, Jamestown, Lancaster"},
	717: {"PA", "USA", -5, "Harrisburg, York, Lancaster"},
	718: {"NY", "USA", -5, "New York City (Bronx, Brooklyn, Queens, Staten Island)"},
	719: {"CO", "USA", -7, "Colorado Springs, Pueblo, Lamar"},
	720: {"CO", "USA", -7, "Overlay of 303 area code."},
	724: {"PA", "USA", -5, "Greensburg, Uniontown, Butler, Washington, New Castle, Indiana"},
	727: {"FL", "USA", -5, "Clearwater, St. Petersburg, New Port Richey, Tarpon Springs"},
	731: {"TN", "USA", -6, "Jackson, Dyersburg, Union City, Paris, Brownsville"},
	732: {"NJ", "USA", -5, "New Brunswick, Metuchen, Rahway, Perth Amboy, Toms River, Bound Brook"},
	734: {"MI", "USA", -5, "Ann Arbor, Livonia, Wayne, Wyandotte, Ypsilanti, Plymouth, Monroe"},
	740: {"OH", "USA", -5, "Portsmouth, Newark, Zanesville, Wheeling, Steubenville"},
	747: {"CA", "USA", -8, "Overlay of 818 Area Code."},
	754: {"FL", "USA", -5, "Overlay of 954 Area Code (Ft. Lauderdale Area)."},
	757: {"VA", "USA", -5, "Norfolk, Newport News, Williamsburgh"},
	758: {"", "USA", -5, "St. Lucia"},
	760: {"CA", "USA", -8, "Oceanside, Palm Springs, Victorville, Escondido, Vista, Palm Desert"},
	762: {"GA", "USA", -5, "Overlay of 706 Area Code."},
	763: {"MN", "USA", -6, "Brooklyn Park, Coon Rapids, Maple Grove, Plymouth, Cambridge, Blaine, Anoka"},
	765: {"IN", "USA", -5, "Lafayette, Muncie, Kokomo, Anderson, Richmond, Marion"},
	767: {"", "DMA", -4, "Dominica"},
	769: {"MS", "USA", -6, "Overlay of 601 area code (Southern Mississippi)."},
	770: {"GA", "USA", -5, "Norcross, Chamblee, Smyrna, Tucker, Marietta, Alpharetta, Gainesville"},
	772: {"FL", "USA", -5, "Vero Beach, Port St. Lucie, Stuart, Fort Pierce, Sebastian, Hobe Sound, Jensen Beach, Indiantown"},
	773: {"IL", "USA", -6, "Chicago (except downtown Area is 312)"},
	774: {"MA", "USA", -5, "Overlay of 508 area code."},
	775: {"NV", "USA", -8, "Reno, Carson City"},
	778: {"BC", "CAN", -8, "Overlay of 250 and 604 area codes."},
	779: {"IL", "USA", -6, "Overlay of 815 area code."},
	780: {"AB", "CAN", -7, "Alberta: Edmonton, Fort McMurray, Leduc, Lloydminster, Sherwood Park"},
	781: {"MA", "USA", -5, "Waltham, Lexington, Burlinton, Dedham, Woburn, Lynn, Malden, Saugus, Reading, Braintree, Wellesley"},
	784: {"", "VCT", -5, "St. Vincent & the Grenadines"},
	785: {"KS", "USA", -6, "Topeka, Lawrence, Manhattan, Salina, Junction"},
	786: {"FL", "USA", -5, "Overlay of 305 area code (Miami)."},
	787: {"PR", "PRI", -4, "Puerto Rico: All regions"},
	800: {"", "USA", 0, "Toll Free"},
	801: {"UT", "USA", -7, "Utah: Salt Lake City, Provo, Ogden, Orem, American Fork, Spanish Fork, Bountiful, Kaysville, Morgan"},
	802: {"VT", "USA", -5, "Vermont: All regions"},
	803: {"SC", "USA", -5, "Columbia"},
	804: {"VA", "USA", -5, "Richmond, Lynchburg, Petersburg,"},
	805: {"CA", "USA", -8, "Santa Barbara, Thousand Oaks, San Luis Obispo, Ventura, Oxnard, Simi Valley"},
	806: {"TX", "USA", -6, "Amarillo, Lubbock"},
	807: {"ON", "CAN", -5, "Western Ontario: Thunder Bay"},
	808: {"HI", "USA", -10, "Hawaii: All regions"},
	809: {"", "USA", -4, "Caribbean Islands without their own Area Code (Nevis/St. Kitts)"},
	810: {"MI", "USA", -5, "Flint, Port Huron, Lapeer, Brighton, Sandusky"},
	812: {"IN", "USA", -5, "Evansville, Bloomington, Terre Haute, New Albany"},
	813: {"FL", "USA", -5, "Tampa"},
	814: {"PA", "USA", -5, "Altoona, Johnstown, Erie, Punxsutawney"},
	815: {"IL", "USA", -6, "La Salle, Joliet, Rockford, DeKalb"},
	816: {"MO", "USA", -6, "Kansas City, Saint Joseph, Independence, Gladstone"},
	817: {"TX", "USA", -6, "Fort Worth, Arlington, Euless, Grapevine"},
	818: {"CA", "USA", -8, "Van Nuys, Canoga Park, Burbank, San Fernando, Glendale, N. Hollywood"},
	819: {"QC", "CAN", -5, "Hull, Sherbrooke, Trois-Riviers, Gatineau"},
	828: {"NC", "USA", -5, "Asheville, Hickory, Morganton, Hendersonville, Lenoir, Boone, Andrews, Murphy, Marble"},
	829: {"", "DOM", -4, "Dominican Republic"},
	830: {"TX", "USA", -6, "New Braunfels, Del Rio, Seguin, Kerrville, Eagle Pass, Fredericksburg"},
	831: {"CA", "USA", -8, "Monterey, Santa Cruz, Salinas, Hollister, Aptos, Carmel"},
	832: {"TX", "USA", -6, "Overlay of 713, 281 Area Codes (Houston)."},
	843: {"SC", "USA", -5, "Charleston, Florence, Myrtle Beach, Hilton Head"},
	845: {"NY", "USA", -5, "Poughkeepsie, Spring Valley, Newburgh, Kingston, Nyack, Middletown, Brewster, Pearl River"},
	847: {"IL", "USA", -6, "Northbrook, Skokie, Evanston, Glenview, Waukegan, Desplaines, Elk Grove (North suburbs of Chicago)"},
	848: {"NJ", "USA", -5, "Overlay of 732 area code."},
	849: {"", "DOM", -4, "Dominican Republic"},
	850: {"FL", "USA", -6, "Tallahassee, Pensacola, Fort Walton Beach, Panama City"},
	855: {"", "USA", 0, "Toll Free"},
	856: {"NJ", "USA", -5, "Camden, Haddonfield, Moorestown, Merchantville, Vineland, Laurel Springs"},
	857: {"MA", "USA", -5, "Overlay of 617 area code."},
	858: {"CA", "USA", -8, "La Jolla, Rancho Bernardo, del Mar, Poway, Rancho Penasquitos, Rancho Santa Fe"},
	859: {"KY", "USA", -5, "Lexington, Covington, Boone, Winchester, Richmond, Danville, Mount Sterling"},
	860: {"CT", "USA", -5, "Hartford, New London, Norwich, Middletown, Bristol"},
	862: {"NJ", "USA", -5, "Overlay of 973 area code."},
	863: {"FL", "USA", -5, "Lakeland, Winter Haven, Lake Wales, Sebring, Haines City, Bartow, Avon Park, Okeechobee, Wachula"},
	864: {"SC", "USA", -5, "Greenville, Spartanburg, Anderson"},
	865: {"TN", "USA", -5, "Knoxville, Maryville, Oak Ridge, Sevierville, Gatlinburg, Concord, Powell"},
	866: {"", "USA", 0, "Toll Free"},
	867: {"YT", "CAN", -8, "Yukon, Northwest Territories: Whitehorse, Yellow Knife, Nunavut"},
	868: {"", "TTO", -4, "Trinidad and Tobago"},
	869: {"", "USA", -5, "Nevis & St. Kitts"},
	870: {"AR", "USA", -6, "Texarkana, Jonesboro, Pine Bluff, El Dorado"},
	872: {"IL", "USA", -6, "Overlay of 312 and 773 area codes."},
	873: {"QC", "CAN", -5, "Overlay of 819 Area Code"},
	876: {"", "JAM", -5, "Jamaica\n877,,USA,0,"},
	878: {"PA", "USA", -5, "Overlay of 412, 724 area codes."},
	880: {"", "USA", 0, "Carribean to U.S. or Canada OR Canada to U.S. Toll Free"},
	881: {"", "USA", 0, "Carribean to U.S. or Canada OR Canada to U.S. Toll Free"},
	888: {"", "USA", 0, "Toll Free"},
	900: {"", "USA", 0, "Used for Mass Calling Value Added Information"},
	901: {"TN", "USA", -6, "Memphis, Collierville"},
	902: {"NS", "CAN", -4, "Nova Scotia, Prince Edward Island"},
	903: {"TX", "USA", -6, "Longview, Tyler, Texarkana, Paris, Kilgore, Sherman, Denison"},
	904: {"FL", "USA", -5, "Jacksonville, Saint Augustine, Orange Park, Fernandina Beach"},
	905: {"ON", "CAN", -5, "Ontario: Hamilton, Niagara Falls, Markham, Mississauga, Brampton"},
	906: {"MI", "USA", -5, "Marquette, Iron Mountain, Houghton, Sault Ste Marie"},
	907: {"AK", "USA", -9, "Alaska: All regions"},
	908: {"NJ", "USA", -5, "Elizabeth, New Brunswick, Somerville, Freehold, Unionville, Plainfield"},
	909: {"CA", "USA", -8, "San Bernardino, Ontario, Upland, Pomona, Riverside, Colton, Chino"},
	910: {"NC", "USA", -5, "Fayetteville, Wilmington, Jacksonville, Lumberton, Laurinburg, Southern Pines"},
	912: {"GA", "USA", -5, "Savannah, Macon, Waycross, Brunswick, Statesboro, Vidalia"},
	913: {"KS", "USA", -6, "Melrose, Kansas City"},
	914: {"NY", "USA", -5, "Westchester, Monroe, Mount Vernon, Mount Kisco, Pleasantville"},
	915: {"TX", "USA", -7, "El Paso, Socorro, Fabens, Dell City, Van Horn, Fort Bliss"},
	916: {"CA", "USA", -8, "Sacramento, Roseville, Fair Oaks, Folsom, Elk Grove, South Placer"},
	917: {"NY", "USA", -5, "Overlay of 212/718 (New York City - cellular/pager only)"},
	918: {"OK", "USA", -6, "Tulsa, Broken Arrow, Muskogee, Bartlesville, McAlester"},
	919: {"NC", "USA", -5, "Raleigh, Durham, Cary, Chapel Hill, Goldsboro, Apex, Sanford, Wake Forest"},
	920: {"WI", "USA", -6, "Green Bay, Appleton, Racine, Fond du Lac, Oshkosh, Sheboygan"},
	925: {"CA", "USA", -8, "Walnut Creek, Pleasanton, Concord, Livermore, Bishop Ranch, Danville, Antioch"},
	928: {"AZ", "USA", -7, "Yuma, Flagstaff, Prescott, Sedona, Bullhead City, Kingman, Lake Havasu City"},
	929: {"NY", "USA", -5, "Overlay of 718 Area Code (Bronx, Brooklyn, Queens, Staten Island)."},
	931: {"TN", "USA", -6, "Clarksville, Shelbyville, Cookeville, Columbia"},
	936: {"TX", "USA", -6, "Conroe, Nacogdoches, Huntsville, Lufkin, Madisonville"},
	937: {"OH", "USA", -5, "Dayton, Springfield, Bellefontaine, Beavercreek, Franklin"},
	938: {"AL", "USA", -6, "Overlay of 256 area code."},
	939: {"PR", "PRI", -4, "Overlay of 787 area code."},
	940: {"TX", "USA", -6, "Wichita Falls, Denton, Gainesville"},
	941: {"FL", "USA", -5, "Sarasota, Bradenton, Venice, Port Charlotte, Punta Gorda"},
	947: {"MI", "USA", -5, "Overlay of 248 Area Code."},
	949: {"CA", "USA", -8, "Irvine, Saddleback Valley, Newport Beach, Capistrano Valley, Laguna Beach"},
	951: {"CA", "USA", -8, "Riverside, Corona, Temecula, Arlington, Hemet, Moreno Valley, Murietta, Sun City, Elsinore"},
	952: {"MN", "USA", -6, "Bloomington, Burnsville, Eden Prairie, Minnetonka, Edina, St. Louis Park, Apple Valley"},
	954: {"FL", "USA", -5, "Fort Lauderdale, Hollywood, Pompano Beach, Deerfield Beach, Coral Springs"},
	956: {"TX", "USA", -6, "Brownsville, Laredo, McAllen, Harlingen, Edinburg"},
	970: {"CO", "USA", -7, "Fort Collins, Greeley, Grand Junction, Loveland, Durango, Vail"},
	971: {"OR", "USA", -8, "Overlay of 503 area code."},
	972: {"TX", "USA", -6, "Texas: Dallas Metro (overlays 214/469)"},
	973: {"NJ", "USA", -5, "New Jersey: Newark, Paterson, Morristown (see overlay 862; split from 201)\"\n975,MO,USA,-6,"},
	978: {"MA", "USA", -5, "Massachusetts: north of Boston to NH (see split 978 -- this is the northern half of old 508; see overlay 351)"},
	979: {"TX", "USA", -6, "SE Texas: Bryan, College Station, Bay City (split from 409, see also 936)"},
	980: {"NC", "USA", -5, "North Carolina: (overlay on 704; perm 5/1/00, mand 3/15/01)"},
	984: {"NC", "USA", -5, "E North Carolina: Raleigh (overlaid on 919, perm 8/1/01, mand 2/5/02 POSTPONED)"},
	985: {"LA", "USA", -6, "E Louisiana: SE/N shore of Lake Pontchartrain: Hammond, Slidell, Covington, Amite, Kentwood, area SW of New Orleans, Houma, Thibodaux, Morgan City (split from 504; perm 2/12/01; mand 10/22/01)"},
	989: {"MI", "USA", -5, "Upper central Michigan: Mt Pleasant, Saginaw (split from 517; perm 4/7/01)"},
}

func GetAreaCode(pnStr string) int {
	result := 0
	result += int(pnStr[0]-'0') * 100
	result += int(pnStr[1]-'0') * 10
	result += int(pnStr[2]-'0') * 1
	return result
}
